# Generated by Django 5.0.14 on 2025-08-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateory',
            new_name='category',
        ),
    ]
